name: Build and deploy ASP.NET Core Blazor app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish .NET project
        run: dotnet publish ./src/UnixphileLearn -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'unixphile-learn'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./publish

