name: Build and deploy to Azure App Services

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: src/UnixphileLearn/package-lock.json

      - name: Install Tailwind dependencies
        run: npm ci
        working-directory: src/UnixphileLearn

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Publish .NET project
        run: dotnet publish ./src/UnixphileLearn -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'unixphile-learn'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./publish

